// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddFocusRequest struct {
	Title    string `form:"title"`
	Pic      string `form:"pic"`
	Link     string `form:"link"`
	Position int    `form:"position"`
}

type CommonResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
	Success bool        `json:"success"`
}

type Focus struct {
	Id       int    `json:"id"`
	Title    string `json:"title"`
	Pic      string `json:"pic"`
	Link     string `json:"link"`
	Position int    `json:"position"`
}

type FocusRequest struct {
	Id int `form:"id"`
}

type FocusRequestById struct {
	Id int64 `path:"id"`
}

type UpdateFocusRequest struct {
	Id       int    `form:"id"`
	Title    string `form:"title"`
	Pic      string `form:"pic"`
	Link     string `form:"link"`
	Position int    `form:"position"`
}

type UserRequest struct {
	UserName string `json:"username"`
	PassWord string `json:"password"`
}
