// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	focus "go-gorm/internal/handler/focus"
	user "go-gorm/internal/handler/user"
	"go-gorm/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取轮播图
				Method:  http.MethodGet,
				Path:    "/",
				Handler: focus.GetFucusHandler(serverCtx),
			},
			{
				// 根据id获取轮播图
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: focus.GetFucusByIdHandler(serverCtx),
			},
			{
				// 新增轮播图
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: focus.AddFucusHandler(serverCtx),
			},
			{
				// 删除轮播图
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: focus.DeleteFucusHandler(serverCtx),
			},
			{
				// 修改轮播图
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: focus.UpdateFucusHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/focus"),
		rest.WithJwt(serverCtx.Config.Auth.Secret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取轮播图
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)
}
